### ISSUE TITLE
Week 1 Review Ticket - Brian

### ISSUE THREAD

**Issue by BrianZhang2016** [PunarvasuS/PopcornCritics#22]
# SCORE FOR THE WEEK: 4.7/5 (TEAM: 1.8/2 and INDIVIDUAL 2.9/3)
# INDIVIDUAL SCORE = 2.9/3, REVIEWED BY Alex Do FOR Brian Zhang
## Individual GitHub pages (3 points)
- GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions
  - [x] One Check 5.3
  - [x] One Check 5.4
- GitHub page that documents key learnings and code snippets using GitHub and replit.
  - [x] InfoDB lists
  - [x] One Check for New Data, minimum of 4 items
- InfoDB loops
  - [x] One Check For Loop running and sensible output
  - [x] One Check While Loop running and sensible output
  - [x] One Check Recursion running and sensible output
    - Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
  - [x] Four checks:
    - Algorithm and code with comments
    - Prints result
    - Prints Complete List
    - Work on complex sequence with multiple words, spaces, special characters
  - [x] One check: comments and documentation throughout

**Comment by AlexD017** [comment]
# Score = 2.8/3, Reviewed by Alex Do
# Individual GitHub pages (3 points)

* GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions
- [x] 1- One Check 5.3
- [x] 1- One Check 5.4

* GitHub page that documents key learnings and code snippets using GitHub and replit. 
- [x] InfoDB lists
- [x] 1 - One Check for New Data, minimum of 4 items

* InfoDB loops
- [x] 1- One Check For Loop running and sensible output
- [x] 1- One Check While Loop running and sensible output
- [x] 1- One Check Recursion running and sensible output

* Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
- [x] 4- Four checks: Algorithm and code with comments, Prints result, Prints Complete List, Work on complex sequence with multiple words, spaces, special characters
- [x] 1- One check: comments and documentation throughout
