### ISSUE TITLE
Week 1 Review Ticket - Nathan

### ISSUE THREAD

**Issue by ProRichyMan** [PunarvasuS/PopcornCritics#23]
## SCORE = 3/3, REVIEWED BY James Lee FOR Nathan Manangan

# TANGIBLES FOR:
TEST PREP - [NOTES](https://prorichyman.github.io/NathanIndividual/week0)
INFODB LISTS - [CODE](https://replit.com/@ProRichyMan/menu#InfoDb.py)
ALGORITHMS WITH PRINTS - [CODE](https://replit.com/@ProRichyMan/menu#InfoDb.py)

# [GITHUB PAGE](https://prorichyman.github.io/NathanIndividual/)

**Comment by JL1080** [comment]
### SCORE = 3/3, REVIEWED BY James Lee FOR Nathan 
- GitHub page for Test Prep study, requiring [5.3, 5.4 notes and actions.](https://punarvasus.github.io/DataStructures/tps)
  - [x] One Check 5.3
  - [x ] One Check 5.4
- GitHub page that documents key learnings and code snippets using GitHub and replit.
  - [x] InfoDB lists
  - [x ] One Check for New Data, minimum of 4 items  InfoDB loops
  - [x ] One Check For Loop running and sensible output
  - [x ] One Check While Loop running and sensible output
  - [x ] One Check Recursion running and sensible output
    - Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
  - [x] Four checks:
    - Algorithm and code with comments
    - Prints result
    - Prints Complete List
    - Work on complex sequence with multiple words, spaces, special characters
  - [x] One check: comments and documentation throughout

**Comment by ProRichyMan** [comment]
TANGIBLES FOR:
TEST PREP - [NOTES](https://prorichyman.github.io/NathanIndividual/week0)
INFODB LISTS - [CODE](https://replit.com/@ProRichyMan/menu#InfoDb.py)
ALGORITHMS WITH PRINTS - [CODE](https://replit.com/@ProRichyMan/menu#InfoDb.py)
