### ISSUE TITLE
Week 2 Individual Review Brian Zhang

### ISSUE THREAD

**Issue by BrianZhang2016** [PunarvasuS/PopcornCritics#26]
# Total Score: 4.3/5       Individual Who Graded Me: Evan Sanchez

## Individual Score Below

**Comment by deimie** [comment]
- [ ] GitHub page that documents key learnings and code snippets using GitHub and replit

- [ ] Organize files, directories and menus for the first 3 weeks.

- [ ] Write Factorial function using classes, providing implementation of call.

- [ ]  Select your own Math function. Write it in Imperative and OOP form.

- [ ] Extra Credit. Write Palindrome function using classes, must provide implementation of call. Must indicate where error occurs on front and back comparison.

Score: 4.5/5
Math function only written in OOP and not imperative.
