### ISSUE TITLE
Week 2 Review - Derrick Huang

### ISSUE THREAD

**Issue by Pitsco** [PunarvasuS/PopcornCritics#28]
Peer Evaluater: Armaan Shamsaseef
Total Score: 4.8/5
Individual Score: 3/3
Team Score: 1.8/2
Scrum Team GitHub pages (2 points)
 
Project Owner / Sponsor presentation(visuals like wireframes or HTML pages), results of review, PII concerns, hosting plan, and software license

1st Code in GitHub with software license per 5.5

Individual GitHub pages (3 points)
 GitHub page that documents key learnings and code snippets using GitHub and replit (See Challenges at the bottom of [TT2 (Links to an external site.)](https://github.com/nighthawkcoders/nighthawk_csp/wiki/Tri-3-TT2-Python-Classes) for details)

- [ ]  Organize files, directories and menus for the first 3 weeks.
- [ ] Write Factorial function using classes, providing implementation of call.
- [ ] Select your own Math function. Write it in Imperative and OOP form.
- [ ] Extra Credit. Write Palindrome function using classes, must provide implementation of call. Must indicate where error occurs on front and back comparison.

**Comment by xXAASXx** [comment]
Total Score 4.8/5
Derrick you did a great job organizing the files, implementing class and I love that you challenged yourself to doing the extra credit but your code does not show the palindrome being false. So I am giving you some credit on the Extra Credit which is enough to give you a 3/3. The only thing I can recommend is adding more clear comments to what the code is doing as some are long and hard to understand for people that don't know the code. 
Team Score was a 1.8/2 with Mr. Mortenson
Individual Score was 3/3
