### ISSUE TITLE
Week 2 Individual - Nathan

### ISSUE THREAD

**Issue by ProRichyMan** [PunarvasuS/PopcornCritics#29]
Total Score: 4.8/5
Individual Score: 2.8/3 ( GRADED BY : Armaan, He also graded Derrick )
Team Score: 2/2

[MY github page](https://prorichyman.github.io/NathanIndividual/)

Individual GitHub pages (3 points) - Checkpoint Grading
- [x] Organize files, directories and menus for the first 3 weeks.
- [x] Write Factorial function using classes, providing implementation of call.
- [x] Select your own Math function. Write it in Imperative and OOP form

Tangibles:
- [LINK for files which has folders for weeks and organization](https://replit.com/@ProRichyMan/menu#main.py)
- [LINK to factorial.py](https://replit.com/@ProRichyMan/menu#week2/factorial.py)
- [LINK to combo.py](https://replit.com/@ProRichyMan/menu#week2/combo.py)

**Comment by xXAASXx** [comment]
Total Score 4.8/5
Derrick you did a great job organizing the files, implementing class and I love that you challenged yourself to doing the extra credit but your code does not show the palindrome being false. So I am giving you some credit on the Extra Credit which is enough to give you a 3/3. The only thing I can recommend is adding more clear comments to what the code is doing as some are long and hard to understand for people that don't know the code.
Team Score was a 1.8/2 with Mr. Mortenson
Individual Score was 3/3
