### ISSUE TITLE
Week 3 Indi - Algorithm Final || Punarvasu Sangam

### ISSUE THREAD

**Issue by PunarvasuS** [PunarvasuS/PopcornCritics#30]
# Total Score: 9.9/10 (Graded by: BRIAN TANG)

## Individual Coding:
- [x] [GitHub Pages](https://punarvasus.github.io/DataStructures) showing key learnings and challenges conquered from Tech Talks
- [x] [GitHub commits](https://github.com/PunarvasuS/Menu/commit/51b02e9646397fa1d6a3b1d9a30af0f8f1ec4a85) you have made, show GitHub insights into your code commits.
 - forgot to link Menu Replit and GitHub until Week 3; commits don't show anything useful (everything is just one massive commit)
- [x] Show Code running on [Replit](https://replit.com/@LordPotashmallo/Menu) as well as IntelliJ
- [x] [Menu](https://replit.com/@LordPotashmallo/Menu#main.py) review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- [x] [List and Loops:](https://replit.com/@LordPotashmallo/Menu#week_1/infodb.py) show runtime, code organization, code and comments
- [x] [Class review and understanding:](https://replit.com/@LordPotashmallo/Menu#week_2/combo,py) show runtime, code organization, code and comments
- [x] [Show Crossover contribution:](https://github.com/bgt072105/curly-ladle/pull/4) Highlight work you did in crossover project: show their [Replit runtime](https://replit.com/@bgt072105/curly-ladle), [code commit(s)](https://github.com/bgt072105/curly-ladle/commits/main) in their [GitHub repo](https://github.com/bgt072105/curly-ladle/).
Show anything you have done to enhance what you have [learned](https://replit.com/@LordPotashmallo/Menu#week_2/palindrome.py) from Python code
- [x] Make sure you cover everything, but create your own order and optimize time
- [x] Use Voice or Captions.   Try not to wiggle mouse a lot or over scroll.  Make sure you have a clear plan before you start.
- [x] Perform video in small parts 15-30 seconds and finish a key subject.  Then put the final Video together with Video editing or Youtube playlists.

**Comment by bgt072105** [comment]
Total Score: 9.9/10 (Graded by: BRIAN TANG)

All work has been completed. Only comment for improvement is that Replit was not linked to GitHub until recently, so all work just shows up as a single commit.

**Comment by bgt072105** [comment]
- [x]  [GitHub Pages](https://bgt072105.github.io/curly-ladle/) showing key learnings and challenges conquered from Tech Talks
- [x]  [GitHub commits](https://github.com/bgt072105/curly-ladle/graphs/contributors) you have made, show GitHub insights into your code commits.
- [x] Show Code running on [Replit](https://replit.com/join/shwebjagoo-bgt072105) as well as IntelliJ
- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- [x] List and Loops: show runtime, code organization, code and comments
- [x] Class review and understanding: show runtime, code organization, code and comments
- [x] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo. Show anything you have done to enhance what you have learned from Python code
- [x] Make sure you cover everything, but create your own order and optimize time
- [x] Use Voice or Captions.   Try not to wiggle mouse a lot or over scroll.  Make sure you have a clear plan before you start.
- [x] Perform video in small parts 15-30 seconds and finish a key subject.  Then put the final Video together with Video editing or Youtube playlists.

**Comment by jm1021** [comment]
t was funny to see you welcome and waving animations.  Also, you spent a little slow down show how you used regular expression in Palindrome.  It is great to see you emphasize interests.  You could have spoke a little bit more about Class code as similar emphasis.
I looked at you GitHub pages and I liked you submenu on Data Structures project.   Your grader did not enumerate things you covered on video,  You should make sure that happens.
I could not find your code easily in GitHub.  I did see code on ReplIt.  Also, I don't remember you showing me code running in multiple places.  Mostly, stuff looks good but there seems to be some things missing.
9/10
