### ISSUE TITLE
Week 3 Individual Final - Nathan

### ISSUE THREAD

**Issue by ProRichyMan** [PunarvasuS/PopcornCritics#31]
### MY VIDEO - https://youtu.be/KfwqwhG1ViQ

Github Pages - 
My Individual Github Page: https://prorichyman.github.io/NathanIndividual/
Notes + Actions Page: https://prorichyman.github.io/NathanIndividual/section5

My Review Tickets -
Week 0: https://github.com/PunarvasuS/PopcornCritics/issues/6
Week 1: https://github.com/PunarvasuS/PopcornCritics/issues/23
Week 2: https://github.com/PunarvasuS/PopcornCritics/issues/29

Commits -
Github Pages Commits: https://github.com/ProRichyMan/NathanIndividual/commits/main
Replit Commits (Doesn't have many because I originally made the Replit without linking it to Github, so I remade it): https://github.com/ProRichyMan/Nathanreplit/commits/main

My Replit -
Replit Page - https://replit.com/@ProRichyMan/Nathanreplit#main.py

Crossover Work -
Crossover Commits: https://github.com/AlexD017/Tri3-IndivRepo/commits?author=ProRichyMan
Crossover Repo:  https://replit.com/@AlexDo8/Tri3-IndivRepo#replit/main.py

**Comment by xXAASXx** [comment]
# Score- 9.8/10
Just needed to show contributions as well as commits but overall the video was edited well and it was very easy to navigate and grade the things that you have done.

**Comment by AlexD017** [comment]
# Score: 10/10 Graded by Alex Do
The video showed everything needed for the review. Could've shown more for own github page and extend the video length. 
### Individual Coding:

- [x] GitHub Pages showing key learnings and challenges conquered from Tech Talks

- [x] GitHub commits you have made, show GitHub insights into your code commits.

- [x] Show Code running on Replit as well as IntelliJ

- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments

- [x] List and Loops: show runtime, code organization, code and comments

- [x] Class review and understanding: show runtime, code organization, code and comments

- [x] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their 

- [x] GitHub repo. Show anything you have done to enhance what you have learned from Python code

- [x] Video 2 minutes: showing the above, quality suggested as follows

- [x] Make sure you cover everything, but create your own order and optimize time

**Comment by AlexD017** [comment]
# Score: 9.9/10 Akhil's video Graded by Alex Do
Comment: Could've shown his own commits from their crossover's repository 
### Individual Coding:

- [x] GitHub Pages showing key learnings and challenges conquered from Tech Talks

- [x] GitHub commits you have made, show GitHub insights into your code commits.

- [x] Show Code running on Replit as well as IntelliJ

- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments

- [x] List and Loops: show runtime, code organization, code and comments

- [x] Class review and understanding: show runtime, code organization, code and comments

- [x] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their 

- [x] GitHub repo. Show anything you have done to enhance what you have learned from Python code

- [x] Video 2 minutes: showing the above, quality suggested as follows

- [x] Make sure you cover everything, but create your own order and optimize time

**Comment by jm1021** [comment]
Nathan, first off I like your positive energy in class.  Most of the time you seem to be engaged in lectures and know tasks.   Your video making skills and plan for presenting was amazing.  Your technical words and descriptions are getting to be very strong.   Only exception to this is when you spoke about classes and recursion, seem like you could have spent another 10-15 seconds on this VERY IMPORTANT topic.   Similar to how you pointe and illustrated command of imports and the functions in the menu.
Looking at your GitHub pages is very impressive.  I can see you put thought into organization and how you wanted things to look.  It was naturally easy for me to see your organization.  A good design does not need instruction and you have that.   Only comment, is the home pages seems like it needs a little introduction blurb/message.  But, not to much as it is not the your style.
Regarding you REPL and code.  It seems like your menu with misc title and lack of comments in the entire section, plus minimized comments in the video make me feel you have not really owned this code yet.  This all lack the quality, organization, and command that I see in you and your other work.   Functions or Classes need comments and names like everything else that shows understanding.
In all, I like your work.  Great job.   9/10
