### ISSUE TITLE
Week 3 Algorithmic Final- Brian Zhang

### ISSUE THREAD

**Issue by BrianZhang2016** [PunarvasuS/PopcornCritics#33]
# Score: 9.8/10   Graded By: Armaan Shamsaasef

## Video: https://www.youtube.com/watch?v=nx_WzCntwNw
Deployed Github Pages: https://brianzhang2016.github.io/Brian-Individual/
Notes: https://brianzhang2016.github.io/Brian-Individual/pages/notes
Week 0 Review Ticket: https://github.com/PunarvasuS/PopcornCritics/issues/3
Week 1 Review Ticket: https://github.com/PunarvasuS/PopcornCritics/issues/22
Week 2 Review Ticket: https://github.com/PunarvasuS/PopcornCritics/issues/26
Github Pages Commits: https://github.com/BrianZhang2016/Brian-Individual/commits/gh-pages
Replit Commits: https://github.com/BrianZhang2016/Menu/commits/main
Replit Page: https://replit.com/@BrianZhang2016
Crossover Commits: https://github.com/deimie/individual/commits/main

# Grading Akhil Nandhakumar       Score: 
## Video https://youtu.be/SJqbC-DlWFU

**Comment by xXAASXx** [comment]
# Score- 9.9/10
Just needed to show contributions in GitHub Insights. I feel that because you said in the video that you could not get IntelliJ running till later I can understand the commits not looking too good. At the end of the day, you did an amazing job and the score you got reflects this. Keep up the good work.

**Comment by xXAASXx** [comment]
# Grade For Ackil Nandakumar
# Score 9.9/10

WOW!!!!
- This video cannot possibly be better as it not only shows all the tasks but is well organized with timestamps which are really impressive. Your voice in the background also is very clear so following along with you is amazing. The only thing that you are missing is the code commits on your crossover Github Repo.
