### ISSUE TITLE
Week 4&5 Create Task and Log-In -Brian Zhang

### ISSUE THREAD

**Issue by BrianZhang2016** [PunarvasuS/PopcornCritics#36]
# Score: 4.5/5 Graded By: Linda Liu

## [Link to Create Task Written Response](https://brianzhang2016.github.io/Brian-Individual/pages/writtenresponse)

* CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x] CB Create Task Coding requirements documented
  - GitHub page contains requirements
  - **1/1**
- [x] Runtime of Code(with comments) on Replit/Intellij
  - Runtime on Replit with comments
  - **1/1**
* Accounts and Logins Challenges/Hacks ( 3 Points - Team)
- [x]  Hack 1 Add Phone Number to Sign Up / Authorization screen
  - Sign up page contains phone number input box
  - **1/1**
- [ ] Hack 2 Add logout to CRUD screen
  - Logout attempted but doesn't work as intended
  - **0.5/1**
- [x] Hack 3 Add login_required to another portion of the project
  - Login page added to crud table page
  - **1/1**

**Comment by LindaLiu1202** [comment]
crossover grading
