### ISSUE TITLE
Week 4/5 Individual Review Ticket || Punarvasu Sangam

### ISSUE THREAD

**Issue by PunarvasuS** [PunarvasuS/PopcornCritics#37]
# TOTAL SCORE : 4/5; Graded By: KATIE HICKMAN For: PUNARVASU SANGAM
## CB Create Task completed and documented on [GH Pages](https://punarvasus.github.io/DataStructures/createtask) - Prep to submit to CB on or before May, 2nd. (2/2)
- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on [Replit](https://replit.com/@LordPotashmallo/Menu#tri2/createtask.py)/Intellij
## Accounts and Logins Challenges/Hacks (2.5/3)
- [x] Hack 1 Add Phone Number to Sign Up / Authorization screen
- [ ] Hack 2 Add logout to CRUD screen
- [x] Hack 3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by katiehickman** [comment]
Grader: Katie Hickman 
Grade: 4.9/5

All code is complete and has great comments. Only thing missing is hack 2. No extra credit. Create task is completed well with comments
