### ISSUE TITLE
Nathan Individual Test Plan

### ISSUE THREAD

**Issue by ProRichyMan** [PunarvasuS/PopcornCritics#40]
# Score 5/5 (Graded by: Brian Zhang)

Github Page Link - [Notes](https://prorichyman.github.io/NathanIndividual/notes)

### AP Test
AP Test 1 (45/50) - [Corrections](https://prorichyman.github.io/NathanIndividual/test1)
AP Test 1 (46/50) - [Corrections](https://prorichyman.github.io/NathanIndividual/test2)
Week Plan - [AP Plan](https://prorichyman.github.io/NathanIndividual/testprep)

### Create Task
Create Task Content - [Github Page](https://prorichyman.github.io/NathanIndividual/createtask)
Video - https://user-images.githubusercontent.com/89236893/165161541-2d438b39-f5c8-4d1d-a18d-171aaaac3187.mp4

- [x] Start review ticket with study plan and study reflection for week, due EOD Monday 4/18 (1/1)
- [x] Finals-Quiz1 score/50 and corrections (1/1)
- [x] Finals-Quiz2 score/50 and corrections (1/1)
- [x] Create Task code/runtime and 1 min video are reviewed by another person, you may request Teacher review as time permits (1/1)
- [x] Review ticket with Crossover Score on Monday 4/25 in class (1/1)

Reflection:
I think my plan for study went well, as my score this time around the MCQ was a lot better than my previous tests, and I ended up performing better on problems I reviewed. However, I do believe I need review on topic we haven't covered in a while, because some topics ended up confusing me a lot, resulting in a lower score than I expected.

**Comment by BrianZhang2016** [comment]
# Score 5/5 Grader: Brian Zhang

- [ ] Study plan [Here](https://prorichyman.github.io/NathanIndividual/testprep)
- [ ] Study reflection for week: Listed at the bottom of this issue
- [ ] Finals-Quiz1 score/50 and corrections: [Link](https://prorichyman.github.io/NathanIndividual/test1)
- [ ] Finals-Quiz2 score/50 and corrections: [Link](https://prorichyman.github.io/NathanIndividual/test2)
- [ ] Create Task code/runtime and 1 min video: [Video](https://user-images.githubusercontent.com/89236893/165161541-2d438b39-f5c8-4d1d-a18d-171aaaac3187.mp4)
