### ISSUE TITLE
Week 6 Indi Review Ticket || Punnu

### ISSUE THREAD

**Issue by PunarvasuS** [PunarvasuS/PopcornCritics#41]
# CROSSOVER GRADE: 4.4/5 by LINDA LIU for PUNARVASU SANGAM
## GH Page -  [Corrections](https://punavasus.github.io/DataStructures/aptest)
Practice Test 1 (47/50)
Practice Test 2 (45/50)

## Study Plan
Do tests, do corrections, study over weekend for Week 6 practice tests

## Study Reflection
I did pretty good on the tests (45/50 & 47/50). I studied a little, but not much, so I think these are good scores. I will study all three tests before the real AP test, so I can absolutely guarantee a 90%< score.

Checks:
- [x] Start review ticket with study plan and study reflection for week, due EOD Monday 4/18 (1/1)
- [x] Finals-Quiz1 score/50 and [corrections](https://punavasus.github.io/DataStructures/aptest) (1/1)
- [x] Finals-Quiz2 score/50 and [corrections](https://punavasus.github.io/DataStructures/aptest) (1/1)
- [x] [Create Task code/runtime](https://replit.com/@LordPotashmallo/CBCreateTask#main.py) and [1 min video](https://drive.google.com/file/d/1PVltaEX5J6o1pTB9W4j07vvzn9cWPGoc/view?usp=sharing) are reviewed by another person, you may request Teacher review as time permits (1/1)
- [x] Review ticket with Crossover Score on Monday 4/25 in class (1/1)

**Comment by LindaLiu1202** [comment]
grading
