### ISSUE TITLE
Individual Study Plan - Brian Zhang

### ISSUE THREAD

**Issue by BrianZhang2016** [PunarvasuS/PopcornCritics#42]
# Score: 4.8/5 Graded by Ritvik Keerthi
## Study Reflection:
I did better on the second test compared to the first as I spent more time studying on Wednesday compared to Monday. This is because seeing my score on the first practice quiz made me realize that I needed to study more than I thought. I then used the college board materials and the questions on the first quiz to help me study for quiz 2.

**Comment by Ritvik-Keerthi** [comment]
Reviewed By: Ritvik Keerthi

TOTAL SCORE: 4.8/5

Start review ticket with study plan and study reflection for week, due EOD Monday 4/18
- Study Plan is very clearly documented on Individual Github Page, as well as has activities for every day from Monday to Friday, listed for all days. Clearly on review ticket, with tangible linked. [Tangible](https://brianzhang2016.github.io/Brian-Individual/pages/studyplan) [SCORE: 1/1]

Finals-Quiz1 score/50 and corrections
- Quiz 1 score clearly documented in review ticket, with corrections obviously linked onto individual page, as well as individual review ticket. Score of 41/50 on review ticket. Quiz 1 corrections have screenshots of questions, with explanations of answers on the github individual page. There could be more explanation and expression of ideas in quiz reflection however. [SCORE: 0.9/1] [Tangible](https://brianzhang2016.github.io/Brian-Individual/quizc/quiz1)

Finals-Quiz2 score/50 and corrections
- Quiz 2 score clearly documented in review ticket, with corrections obviously linked onto individual page, as well as individual review ticket. Score of 45/50 on review ticket. Quiz 2 corrections have screenshots of questions, with explanations of answers on the github individual page. There could be more explanation and expression of ideas in quiz reflection however. [SCORE" 0.9/1] [Tangible](https://brianzhang2016.github.io/Brian-Individual/quizc/quiz2)

Create Task code/runtime and 1 min video are reviewed by another person, you may request Teacher review as time permits
- Create Task fully documented with runtime, video, and written responses all in full detail. Looks like a very good Create Task and has everything documented well. [SCORE: 1/1] [Tangible](https://create-task.brianzhang2016.repl.co/)
