### ISSUE TITLE
Week 4 Create Task + Quizzes Review - Derrick Huang

### ISSUE THREAD

**Issue by Pitsco** [PunarvasuS/PopcornCritics#43]
# Graded by: Armaan, Score: 4.8/5
## Study Reflection:
I significantly did better on the first test compared to the first as I spent more carefully reading the questions. I also didn't finish the second test in time because I didn't finish during the class period and forgot to complete it at home. Seeing my score on the second practice quiz made me realize that I need to manage my time carefully.

**Comment by xXAASXx** [comment]
Total Score: 4.5/5
- You did an amazing job as you have everything here and it is well organized and easy to grade. I like how you changed your create task video from last week and now it is an a lot better video.
