### ISSUE TITLE
Week 6 Review Ticket || Punarvasu Sangam

### ISSUE THREAD

**Issue by PunarvasuS** [PunarvasuS/PopcornCritics#44]
# 4.5/5 Graded by BRIAN ZHANG
- [x] GH Indi Page, Review Ticket, Crossover graded, [Study Plan](https://punarvasus.github.io/DataStructures/aptest) (1/1)
- [x] Create Task and Create Task Crossover Review comments (completed by Thu) (1/1)
  - [my comments](https://github.com/LindaLiu1202/lindaliu/issues/7#issuecomment-1109987987)
  - [their comments](https://github.com/PunarvasuS/PopcornCritics/issues/41#issuecomment-1108981712) 
- [x] Quiz3 MCQ results and [test corrections](https://punarvasus.github.io/DataStructures/aptest) (1/1)
- [x] Participation (1/1)
- [x] Quality of Work (0.5/0.5)
- [ ] Teacher Eval (0.5/0.5)

**Comment by BrianZhang2016** [comment]
# 4.5/5 Graded by Brian Zhang
- [x] GH Indi Page, Review Ticket, Crossover graded, [Study Plan](https://punarvasus.github.io/DataStructures/aptest) (1/1)
- [x] Create Task and Create Task Crossover Review comments (completed by Thu) (1/1)
  - [my comments](https://github.com/LindaLiu1202/lindaliu/issues/7#issuecomment-1109987987)
  - [their comments](https://github.com/PunarvasuS/PopcornCritics/issues/41#issuecomment-1108981712) 
- [x] Quiz3 MCQ results and [test corrections](https://punarvasus.github.io/DataStructures/aptest) (1/1)
- [x] Participation (1/1)
- [x] Quality of Work (0.5/0.5)
