### ISSUE TITLE
Week 7 Review Ticket || Derrick Huang

### ISSUE THREAD

**Issue by Pitsco** [PunarvasuS/PopcornCritics#45]
# Proctored MCQ Week2 : Quiz3 and Create Task review (Grader: Armaan Shamsaasef, Grade: 4.5/5)

- [x] GH Indi Page, Review Ticket, Crossover graded, [Study Plan](https://pitsco.github.io/derrick_individual/examprep)
- [x] Create Task and Create Task Crossover Review comments (completed by Thu)
- [x] Quiz3 MCQ results and [test corrections](https://pitsco.github.io/derrick_individual/quiz3_corrections)
- [x] Ticket

Review Comments with Armaan:
* Video should have some detailed comments
* Writeup should be more detailed, such as including parts of code in my answers
* Create Task seems neat, has a purpose
* Code should have comments but not too much

**Comment by xXAASXx** [comment]
# I believe Derrick has Completed everything correctly and his study plan looks, 

He has completed everything this week including:
[An updated GH Indi Page](https://github.com/Pitsco/derrick_individual/deployments/activity_log?environment=github-pages)
[Created Study Plan](https://pitsco.github.io/derrick_individual/examprep)
Create Task and Create Task Crossover Review comments:
We mainly discussed his video and jotted down some notes. The main thoughts are listed above in Armaan's issue.
Quiz3 MCQ results and [test corrections](https://pitsco.github.io/derrick_individual/quiz3_corrections)
Received a score of 47/50, quiz corrections is on google docs (-0.3)
