### ISSUE TITLE
Week 7 Review Ticket Nathan Manangan

### ISSUE THREAD

**Issue by ProRichyMan** [PunarvasuS/PopcornCritics#46]
# Score 4.5/4.5 (Graded by Ritvik K.)

Github Page Link - [Notes](https://prorichyman.github.io/NathanIndividual/notes)

### AP Test + Corrections
AP Test 1 (45/50) - [Corrections](https://prorichyman.github.io/NathanIndividual/test1)
AP Test 2 (46/50) - [Corrections](https://prorichyman.github.io/NathanIndividual/test2)
AP Test 3 (45/50) - [Corrections](https://prorichyman.github.io/NathanIndividual/test3)

### Create Task Review (Reviewed By: Brian Zhang)

Comments:
- The overview of the program was explained in good detail
- You could have specified the type of list you implemented, also ensure that you have a proper algorithm definition and that you list that each function is clearly stated in written response.
- Overall very good and complete

### Week Plan
Week Plan - [AP Plan](https://prorichyman.github.io/NathanIndividual/testprep)

Monday: Create Task review day, finalize create task after goign over again and submit fully.
Tuesday: Crossover grading, prepare by possibly doing some of the optional MCQ quizzes and over notes.
Wednesday: Proctored AP Exam Day 4
Thursday: Correct test 4, then complete/finish the optional MCQ quizzes if not already, then go over missed questions on day 4.
Friday: Crossover grading, plan to review all units over the weekened for preparation for AP Exam.

**Comment by Ritvik-Keerthi** [comment]
Graded By: Ritvik Keerthi

Has all AP Test Quizzes and Corrections are linked for all
Study Plan is clearly organized
Individual page link is clearly set in place
Good participation in improv ASI

4.5/4.5
