### ISSUE TITLE
Week 6 Review Ticket   Brian Zhang

### ISSUE THREAD

**Issue by BrianZhang2016** [PunarvasuS/PopcornCritics#47]
# Score 4.5/5 Graded By: Punnu Sangam
- [x] GH Indi Page, Review Ticket, Crossover graded, Study Plan (1 Point) [Study Plan](https://github.com/BrianZhang2016/Brian-Individual/blob/gh-pages/pages/studyplan.md)
- [x] Create Task and Create Task Crossover Review comments (completed by Thu) (1 Point) 
[Crossover Review my ticket](https://github.com/PunarvasuS/PopcornCritics/issues/36)
[Crossover Review their ticket](https://github.com/LindaLiu1202/lindaliu/issues/5)
- [x] Quiz3 MCQ results and test corrections (1 Point) [Quiz Correction](https://brianzhang2016.github.io/Brian-Individual/quizc/quiz3)
- [x] Participation (1 Point)
- [x] Quality of work (0.5 Point)
- [x] Teacher Evaluation (0.5 Point)

**Comment by PunarvasuS** [comment]
# Score /5 Graded By: Punnu Sangam
- [ ] GH Indi Page, Review Ticket, Crossover graded, Study Plan (1 Point) [Study Plan](https://github.com/BrianZhang2016/Brian-Individual/blob/gh-pages/pages/studyplan.md)
- [ ] Create Task and Create Task Crossover Review comments (completed by Thu) (1 Point) [Crossover Review](https://github.com/PunarvasuS/PopcornCritics/issues/36)
- [ ] Quiz3 MCQ results and test corrections (1 Point) [Quiz Correction](https://brianzhang2016.github.io/Brian-Individual/quizc/quiz3)
- [ ] Participation (1 Point)
- [ ] Quality of work (0.5 Point)
- [ ] Teacher Evaluation (0.5 Point)
