### ISSUE TITLE
AP Test Week 3 Review Ticket - Derrick Huang

### ISSUE THREAD

**Issue by Pitsco** [PunarvasuS/PopcornCritics#49]
# Score 2/2 (Graded by Punarvasu Sangam)

Github Page Link - [Notes](https://pitsco.github.io/derrick_individual/examprep)

### AP Test + Corrections
AP Test 1 (45/50) - [Corrections](https://pitsco.github.io/derrick_individual/quiz1_corrections)
AP Test 2 (34/50) - [Corrections](https://pitsco.github.io/derrick_individual/quiz2_corrections)
AP Test 3 (42/50) - [Corrections](https://pitsco.github.io/derrick_individual/quiz3_corrections)

## THIS WEEK CORRECTIONS:
AP Test 5 (23/25) - [Corrections](https://pitsco.github.io/derrick_individual/quiz5_corrections)

**Comment by PunarvasuS** [comment]
# SCORE: 2/2

- [x] GH Indi Page, Review Ticket, Crossover graded, Study Plan (1/1)
- [x] Quiz5 MCQ results >50%, (1 or 0) and test corrections (1/1)
