### ISSUE TITLE
AP Exams Week 1 || Punarvasu Sangam

### ISSUE THREAD

**Issue by PunarvasuS** [PunarvasuS/PopcornCritics#50]
# Score ~/2 Graded by Derrick Huang
## Everything is on the [same page](https://punarvasus.github.io/DataStructures/aptest);
- [x] GH Indi Page, Review Ticket, Crossover graded, Study Plan 
- [x] Quiz5 MCQ results >50%, (1 or 0) and [test corrections](https://punarvasus.github.io/DataStructures/aptest)

## AP Test + Corrections
AP Test 1 (45/50)
AP Test 2 (46/50)
AP Test 3 (45/50)
AP Test 4 (24/25)
(2/2)

**Comment by Pitsco** [comment]
2/2

Punarvasu has everything with his MCQ Quiz 5 completed and a score of over 50% with his study plan completed.
