### ISSUE TITLE
Week 1 GitHub Pages

### ISSUE THREAD

**Issue by PunarvasuS** [PunarvasuS/PopcornCritics#9]
Scrum Team Pages
- [x] Project Owner initial requirements, contact info, and derivative tangible plans
- [x] Requirements and Jobs assigned to each individuals listed on Scrum Board, including at least one in progress task

Individual Pages
- GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions
- GitHub page that documents key learnings and code snippets using GitHub and replit.
  - InfoDB lists
  - InfoDB loops
  - Fibonacci
  
  CROSSOVER COMMENT BELOW

**Comment by KoolKidKai** [comment]
Team Pages (/2)

- [ ] Initial requirements, contact info, derivative tangibles

- [ ] requirements and jobs on scrum board with at least one in progress task
Has an

**Comment by jm1021** [comment]
Movie Talk, with backend learning code.   To establish Talk about a current movie.   How do we make this Fresh?   GitHub pages information fresh, time box.  

1.8/2
